name: locaited
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - langgraph>=0.2.0
    - tavily-python>=0.3.0
    - openai>=1.0.0
    - python-dotenv>=1.0.0
    - sqlalchemy>=2.0.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - httpx>=0.24.0
    - pandas>=2.0.0  # For CSV processing